services:
  postgres:
    image: postgres:17
    container_name: bLink-db
    environment:
      POSTGRES_USER: bLink
      POSTGRES_PASSWORD: bLink
      POSTGRES_DB: bLink
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
